import Footer from "@/components/footer/Footer";
import NavbarComponent from "@/components/navbar/Navbar";
import QueryProvider from "@/providers/QueryProvider";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Banner from "./components/Banner";
import StaticInfo from "./components/StaticInfo";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Create Next App</title>
      <body className={inter.className}>
        <QueryProvider>
          <NavbarComponent />
          <Banner />
          <StaticInfo />
          <div className="px-3 bg-gray-50">
            <div className="min-h-screen pb-20 mx-auto max-w-7xl">
              {children}
            </div>
          </div>
          <Footer />
        </QueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
